name: taskX
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  # firebase
  firebase_core: ^2.6.1
  cloud_firestore: ^4.4.2
  firebase_auth: ^4.2.8
  firebase_storage: ^11.0.13
  # service locator
  get_it: ^7.2.0

  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  image_picker: ^0.8.6+2
  flutter_svg: ^2.0.1
  flutter_icons: ^1.1.0
  path_provider: ^2.0.13
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  flutter_native_splash: ^2.2.19
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  badges: ^3.0.2
  percent_indicator: ^4.0.1
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_calendar: ^20.4.53

flutter_intl:
  enabled: true
  class_name: IntlStrings
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
        - asset: assets/fonts/Metropolis-Medium.otf
