name: taskX
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  badges: ^3.0.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.2
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.13
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  flutter_bloc: ^8.1.2
  flutter_icons: ^1.1.0
  # flutter_image_compress: ^1.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.1
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # image_cropper: ^3.0.1
  # image_picker: ^0.8.6+2
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.13
  percent_indicator: ^4.0.1
  provider: ^6.0.5
  # shared_preferences: ^2.0.18
  flutter_speed_dial: ^6.2.0
  syncfusion_flutter_calendar: ^21.1.37
  uuid: ^3.0.7

flutter_intl:
  enabled: true
  class_name: IntlStrings
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - firebase.json

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
        - asset: assets/fonts/Metropolis-Medium.otf
